baseURL = "https://anhub2821.github.io"
title = "Anhub's Personal Page"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
	description = "this is site description"
	copyright = "Copyright Â© 2024 Anhub"
	highlight = true
	custom_css = ["static/css/main.css"]


[menu]

  [[menu.main]]
    name = ""
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "About"
    title = "About Me"
    pageRef = "/about"
    weight = 20

  [[menu.main]]
    name = "Learning"
    title = "Learning"
    pageRef = "/learning"
    weight = 30

#[permalinks]
  #posts = "/:title/"

# [markup.goldmark.renderer]
#	Allows HTML in Markdown
#	 unsafe = true
